import {StyleSheet} from "react-native";


const styles = StyleSheet.create({
        mainBackground: {
            width: '100%',
            height: 847,
            backgroundColor: '#E5E5E5',
        },
        mainSonOne: {
            flexDirection: "row",
            width: '100%',
            justifyContent: 'space-between',
            alignContent: 'center',
            padding: 20,
        },
        clockGroup: {
            flexDirection: "row",
            alignItems: 'center',
            justifyContent: 'space-between',
            margin: 10,
        },
        clockGroupText: {
            marginVertical: 1,
            fontSize: 14,
            paddingLeft: 5,
        },
        clockGroupRectangle: {
            marginTop: 7,
            height: 41,
            width: 112,
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            backgroundColor: '#FFFFFF',
            borderRadius: 30,

            shadowColor: "#FFFFFF",
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.23,
            shadowRadius: 2.62,
            elevation: 4,
        },
        plusGroup: {
            flexDirection: "row",
            alignItems: 'center',
        },
        plusGroupEllipse: {
            width: 55,
            height: 55,
            borderRadius: 55 / 2,
            padding: 10,
            marginLeft: 10
        },
        plusGroupSmallEllipse: {
            width: 20,
            height: 20,
            borderRadius: 25 / 2,
            borderColor: '#8C93A2',
            borderWidth: 1.5,
            borderStyle: 'solid',
            alignItems: 'center',
            marginLeft: 10
        },
        plusGroupNumber: {
            fontSize: 12,
            color: '#8C93A1',
        },
        myAccountText: {
            paddingLeft: 20,
            fontSize: 24,
            color: '#0C0C0E',
            fontWeight: "bold",
        },
        storeGroup: {
            justifyContent: 'space-between',
            alignContent: 'center',
            flexDirection: "row",
            width: '100%',
            padding: 10,
        },
        storeGroupProcent: {
            width: 44,
            height: 22,
            borderRadius: 44 / 2,
            marginBottom: 10,
        },
        heartEllips: {
            position: 'absolute',
            top: '10%',
            left: '11%',
            width: 36,
            height: 36,
            borderRadius: 30,
            padding: 8,
            backgroundColor: 'rgba(0, 0, 0, 0.2)',
        },
        crossEllips: {
            zIndex: 100,
            position: 'absolute',
            left: 160,
            width: 36,
            height: 36,
            borderRadius: 30,
            padding: 8,
            backgroundColor: 'rgba(0, 0, 0, 0.2)',
        },
        whiteBlock: {
            flexDirection: 'row',
            alignItems: 'baseline',
            width: '45%',
            backgroundColor: '#FFFFFF',
            borderRadius: 6,
            marginLeft: 10,
        },
        Rectangle: {
            width: 285,
            height: 159,
            marginTop: 4,
            zIndex: -1,
            right: 10,
        },
        whiteBlockStyle: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-around',
            bottom: 15,
        },
        reStortText: {
            fontSize: 24,
            fontWeight: 'bold',
        },
        electronicsText: {
            color: '#A8ADB7',
            fontSize: 14,
        },
        gradientSon: {
            fontSize: 14,
            fontFamily: 'Gill Sans',
            textAlign: 'center',
            color: '#ffffff',
            backgroundColor: 'transparent',
        },
        ellipseMom: {
            flexDirection: 'row',
            alignItems: 'baseline',
            width: '45%',
            backgroundColor: '#FFFFFF',
            borderRadius: 6,
            marginLeft: 10,
        },
        rectangleImg: {
            width: 285,
            height: 159,
            marginTop: 4,
            zIndex: -1,
            right: 10,
        },
        minBlock: {
            backgroundColor: 'rgba(255,255,255,1)',
            marginLeft: 20,
            width: '90%',
            height: '12%',
            borderRadius: 5,
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            //shadow
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.25,
            shadowRadius: 3.84,

            elevation: 5,
        },
        spendText: {
            color: 'rgba(86,133,253,1)',
            fontSize: 16,
            marginLeft: 30,
            fontWeight: '500',
        },
        moneyText: {
            fontSize: 17,
            marginRight: 20,
            fontWeight: 'bold',
        },
        montBlock: {
            backgroundColor: 'rgba(255,255,255,1)',
            marginLeft: 20,
            width: '90%',
            height: '12%',
            borderRadius: 5,
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: 0.18,
            shadowRadius: 1.0,
            elevation: 1,
        },
        monBlockSize: {
            height: '20%',
            width: '20%',
        },
        mountText: {
            fontSize: 17,
            fontWeight: '500',
        },
        minRight: {
            height: '20%',
            width: '20%',
        },
        barcleyFirst: {
            marginTop: 10,
            marginLeft: 20,
            width: '90%',
            height: '6%',
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
        },
        barclText: {
            color: 'rgb(0,0,0)',
            fontSize: 16,
            fontWeight: 'bold',
        },
        minUp: {
            height: '25%',
            width: '20%',
            paddingLeft: 50,
        },
        cardBlock: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 20,
            marginTop: 15,
        },
        cardStyleOne: {
            zIndex: -1,
            marginLeft: 20,
        },
        visaLogo: {
            height: 12,
            width: 33,
            right: 105,
            marginBottom: 210,
        },
        circleOne: {
            width: 6.5,
            height: 6.5,
            borderRadius: 30,
            backgroundColor: '#ffffff',
            opacity: 0.4,
            marginBottom: 210,
            right: 100,
        },
        circleTwo: {
            width: 6.5,
            height: 6.5,
            borderRadius: 30,
            backgroundColor: '#ffffff',
            opacity: 0.4,
            marginBottom: 210,
            right: 97,
        },
        cardNumber: {
            position: 'absolute',
            opacity: 0.5,
            bottom: 235,
            marginLeft: 170,
            fontSize: 14,
            color: '#FFFFFF',
        },
        moneyCard: {
            position: 'absolute',
            top: '40%',
            marginLeft: 55,
            fontSize: 24,
            color: '#ffffff',
        },
        nameBankCard: {
            position: 'absolute',
            opacity: 0.5,
            top: '52%',
            marginLeft: 85,
            fontSize: 12,
            color: '#FFFFFF',
        },
        positionCard: {
            position: 'absolute',
            left: '8%',
            bottom: "5%",
            width: 46,
            height: 46,
            borderRadius: 30,
            padding: 8,
            backgroundColor: 'rgba(0, 0, 0, 0.2)',
        },
        bankCardBlue: {
            right: 35
        },
        masterCard: {
            right: 105,
            marginBottom: 210,
        },
        circleThree: {
            width: 6.5,
            height: 6.5,
            borderRadius: 30,
            backgroundColor: '#ffffff',
            opacity: 0.4,
            marginBottom: 210,
            right: 100,
        },
        circleFour: {
            width: 6.5,
            height: 6.5,
            borderRadius: 30,
            backgroundColor: '#ffffff',
            opacity: 0.4,
            marginBottom: 210,
            right: 97,
        },
        moneyBlueCard: {
            position: 'absolute',
            top: '40%',
            marginLeft: '70%',
            fontSize: 24,
            color: '#ffffff',
        },
        bankBlueCard: {
            position: 'absolute',
            opacity: 0.6,
            top: '52%',
            marginLeft: '73%',
            fontSize: 12,
            color: '#FFFFFF',
        },
        trashBlueCard: {
            position: 'absolute',
            left: 240,
            bottom: "5%",
            width: 46,
            height: 46,
            borderRadius: 30,
            padding: 8,
            backgroundColor: 'rgba(0, 0, 0, 0.2)',
        },
        barclayTwoPosition: {
            width: '100%',
            height: '3%',
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
        },
        barckBatnkTextTwo: {
            marginLeft: 20,
            color: 'rgb(0,0,0)',
            fontSize: 16,
            fontWeight: 'bold',
        },
        minDown: {
            height: '25%',
            width: '25%',
            paddingLeft: 50,
        },
        lastBlock: {
            backgroundColor: 'rgba(255,255,255,1)',
            marginTop: 10,
            width: '100%',
            height: 80,
            borderRadius: 5,
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: 0.18,
            shadowRadius: 1.0,
            elevation: 1,
        },
        blockImg: {
            marginBottom: 15,
            marginLeft: 25,
        },
        walletImg: {
            position: 'absolute',
            width: 30,
            height: 30,
            marginLeft: 180,
            bottom: 35
        },
        unionImg: {
            height: 25,
            width: 25,
            marginBottom: 5,
            marginRight: 25,
        }
    }
);

export default styles